### ISSUE TITLE
MacOS (Mojave) - Github pull of stan.go repo shows "No Such file or directory" (but exists)

### ISSUE THREAD

**Issue by mmanna-sapfgl** [nats-io/stan.go#256]
I noticed that go-nats-streaming repo is now probably renamed to `stan.go`. When I did the following from my MacOS (Mojave):

`go get GitHub.com\nats-io\stan.go`

I got the following:

`my-MBP:~ mne$ go get github.com/nats-io/stan.go
stat github.com/nats-io/stan.go: no such file or directory`

But when I check the directory - stan.go has been created with the Stan-bench examples and go files. Is there any reason why the error above comes up ? Is it because I already have go-nats-streaming repo from an old pull ?

Thanks,

**Comment by kozlovic** [comment]
@mmanna-sapfgl @derekcollison Nothing what I can do. Unless we revert/update the name of the repo. It seem, though, that the error report has no consequence since things seem to be downloaded and all seem to work. But I agree that this going to cause people to report issues.

**Comment by mmanna-sapfgl** [comment]
Hey no worries - I wasn’t sure if the error was a hard failure. Just ran the bench test, and seems to be working the same.

I’m more than happy to close this.

Sent from my iPhone

On 11 May 2019, at 18:34, Ivan Kozlovic <notifications@github.com<mailto:notifications@github.com>> wrote:


@mmanna-sapfgl<https://github.com/mmanna-sapfgl> @derekcollison<https://github.com/derekcollison> Nothing what I can do. Unless we revert/update the name of the repo. It seem, though, that the error report has no consequence since things seem to be downloaded and all seem to work. But I agree that this going to cause people to report issues.

**Comment by mmanna-sapfgl** [comment]
As per reply from @kozlovic I am closing this since it's got no hard impact on the actual bench testing.

**Comment by coolyrat** [comment]
Hello, I have the same problem, except it didn't download at all. I'm using go mod, and I've tried github.com/nats-io/nats.go as well

**Comment by wallyqs** [comment]
@coolyrat have you tried with `go get github.com/nats-io/stan.go/`?

**Comment by coolyrat** [comment]
@wallyqs My bad, it worked!

**Comment by seguidor777** [comment]
Hello, it is not working that way for me

`$ go get github.com/nats-io/stan.go/`
stat github.com/nats-io/stan.go: no such file or directory

Neither without the `/` at the end or with the `-u` flag
I appreciate any help

**Comment by wallyqs** [comment]
@seguidor777 sorry for the inconvenience, how about with:

```
go get https://github.com/nats-io/stan.go/@latest
```

or: 

```
go get https://github.com/nats-io/stan.go/@v0.5.0
```

**Comment by seguidor777** [comment]
Thank you!

**Comment by wallyqs** [comment]
@seguidor777 glad this worked, btw this is due to this Go issue: https://github.com/golang/go/issues/32483

**Comment by seguidor777** [comment]
I see, good to know, thanks!
