### ISSUE TITLE
Transactional producer support

### ISSUE THREAD

**Issue by mennanov** [nats-io/stan.go#265]
Is there any plan to support a transactional producer in a somewhat similar way it works in Kafka? https://cwiki.apache.org/confluence/display/KAFKA/Transactional+Messaging+in+Kafka

Is this even possible to introduce with the current NATS Streaming implementation?

```go
// does not return until an ack has been received from NATS Streaming
// for _ALL_ the messages at once. 
sc.PublishTx("foo", []byte("msg1"), []byte("msg2")) 
```

Thanks!

**Comment by derekcollison** [comment]
No plans at this time. You can implement your own batching logic however as needed. Are you asking specifically about groups of message either all being sent/delivered or not?

**Comment by mennanov** [comment]
> Are you asking specifically about groups of message either all being sent/delivered or not?

Yes, exactly.

> You can implement your own batching logic however as needed.

Any ideas on how to do that? Except for the obvious one: put all the messages in a single message.

**Comment by derekcollison** [comment]
For Go should be fairly easy to implement a batch publisher that collects messages in slice and then concats and pushed them to STAN in one message and unpacks on the other side.

**Comment by mennanov** [comment]
Thanks for help!
