### ISSUE TITLE
Does PublishAsync() resend messages for which it didn't get an acknowledgement?

### ISSUE THREAD

**Issue by Mr7Sir** [nats-io/stan.go#266]
Hi,
I wanted to know if the publisher will be left on until the server sends an acknowledgement for each message sent via PublishAsync(); and also if PublishAsync() guarantees re-delivery of messages it hasn't gotten an acknowledgement for.

**Comment by kozlovic** [comment]
No, the library does not resend messages. The PublishAsync() by nature does not block and it is the user responsibility to wait on the ack if he/she cares about them. The call may block if more than MaxPubAcksInflight messages have been published without receiving an ack.
