### ISSUE TITLE
error after upgrade

### ISSUE THREAD

**Issue by vtolstov** [nats-io/stan.go#268]
after upgrade to latest stan.go when i'm try to start my app i get error:
```
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.PubMsg
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.PubAck
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.MsgProto
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.Ack
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.ConnectRequest
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.ConnectResponse
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.Ping
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.PingResponse
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.SubscriptionRequest
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.SubscriptionResponse
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.UnsubscribeRequest
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.CloseRequest
2019/05/30 11:46:59 proto: duplicate proto type registered: pb.CloseResponse
panic: proto: duplicate enum registered: pb.StartPosition

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(...)
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/gogo/protobuf/proto/properties.go:509
github.com/nats-io/stan.go/pb.init.0()
        /home/vtolstov/devel/projects/centralv2/vendor/github.com/nats-io/stan.go/pb/protocol.pb.go:263 +0x53a
```

**Comment by vtolstov** [comment]
if i have in the same app two imports one is stan.go and the second import have stan.go import too ?

**Comment by vtolstov** [comment]
problem persists because i have embed stan server (that uses gnatsd imports) and never clients that uses stan.go and nats.go imports.

**Comment by ripienaar** [comment]
ime its entirely unworkable, you have to pin all your dependencies back before the renames happened as right now, its unusable.

**Comment by kozlovic** [comment]
We are really sorry about the inconvenience. I need to publish a server 0.14.3 very soon to fix a cluster/SQL issue, but then the plan is to release nats server 2.0 and quickly followed by a nats-streaming-server that will update all its vendor to the new repos.

In the meantime, have you tried to vendor the streaming client to a rev preceding the repo rename (or the latest release prior to repo name change: https://github.com/nats-io/stan.go/tree/v0.4.4). Would that work.

As a side note, I would be curious how to reproduce this issue. I have created a dir somewhere and a simple content like this, and it compiles/runs ok:
```
package main

import (
	"github.com/nats-io/nats-streaming-server/server"
	"github.com/nats-io/stan.go"
)

func main() {

	s, err := server.RunServerWithOpts(nil, nil)
	if err != nil {
		panic(err)
	}
	defer s.Shutdown()

	sc, err := stan.Connect("test-cluster", "me")
	if err != nil {
		panic(err)
	}
	sc.Close()
}
```

**Comment by vtolstov** [comment]
I don't have now reproduce use-case, i simply sed all imports in vendor folder with new import path and now all works fine. This is ugly but works fine.
No problem - this is my mistake. I think that when you move to go.mod nats-streaming-server without bundled vendor dir, such cases will not happen anymore.

**Comment by vtolstov** [comment]
Do you plan to switch to go.mod when publish 2.0 of nats-streaming-server?

**Comment by kozlovic** [comment]
Yes, will do so after 2.0 is released when updating all dependencies for streaming.

**Comment by bbsbb** [comment]
Hey,

Here is a reproducible example: https://github.com/bbsbb/i-like-it-when-things-work

The above code should demo the issue on any clean go installation(go version 1.12.5). If it's not happening for you, check the go mod cache. I've added the dockerfile as a simple way to trigger the "go: github.com/nats-io/go-nats@v1.8.0: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"" error. 

`docker build -f Dockerfile -t not:working .` should be enough to do it.

The current situation is a bit of a pain. It's easy to deal with in the case of a single repository(with a replace), but in case of shared private dependencies and not a straight forward dependency graph, it quickly becomes unworkable. Let me know if we could help to solve this faster and thanks for the great work on both libraries.

**Comment by kozlovic** [comment]
I think the issue now is with nats.go and stan.go libs not modified to change the nats-server `v2` import as suggested [here](https://github.com/nats-io/nats.go/issues/477#issuecomment-498620833). I can work on that, but I am not 100% sure, so to test it means that I need to create a new tag to test the theory, which if prove wrong means I will have to delete the tag. What do you think?

**Comment by kozlovic** [comment]
Could you guys try again at your earliest convenience? I have issued NATS Streaming v0.15.0, stan.go v0.5.0 and hopefully it now works.
The only problem is that NATS Server is still v2.0.0-RC19 and so NATS Streaming depends on that RC which is bad. As soon that NATS Server is v2.0.0, then I will update Streaming with a v0.15.1 and updated nats server dependency. Apologies for this mess...

**Comment by vtolstov** [comment]
works for me, thanks!

**Comment by kozlovic** [comment]
@vtolstov Thanks for letting me know..

**Comment by bbsbb** [comment]
Same, both are in sync now. Thank you for the super fast reaction!

**Comment by kozlovic** [comment]
Thanks for letting us know and we apologize for the troubles. Glad that it got resolved now.
