### ISSUE TITLE
support go mod

### ISSUE THREAD

**Issue by coolyrat** [nats-io/stan.go#269]
Hello, there's stan.NatsConn(nc *nats.Conn) Option function, need to pass nats.Conn，but now I have to manual execute go get nats.go library. It would be nice to use go mod to handle the dependency.

**Comment by kozlovic** [comment]
Working on that. Thanks!

**Comment by kozlovic** [comment]
https://github.com/nats-io/stan.go/releases/tag/v0.5.0 now has go.mod, hopefully that works for you.

**Comment by biskit** [comment]
hi,
get this message when used with my module...
`go: github.com/nats-io/go-nats-streaming@v0.5.0: parsing go.mod: unexpected module path "github.com/nats-io/stan.go"`

can you check?

**Comment by mmanna-sapfgl** [comment]
It’s okay. Because it was a repo name change last month.

If you browse to your GOPATH, you can see that the location has all files.

Thanks,

Sent from my iPhone

On 5 Jun 2019, at 23:25, biskit <notifications@github.com<mailto:notifications@github.com>> wrote:


hi,
get this message when used with my module...
go: github.com/nats-io/go-nats-streaming@v0.5.0:<http://github.com/nats-io/go-nats-streaming@v0.5.0:> parsing go.mod: unexpected module path "github.com/nats-io/stan.go<http://github.com/nats-io/stan.go>"

can you check?

**Comment by wallyqs** [comment]
Hi @biskit in this repo you can find an example of setting up the deps in go mod using the new names: https://github.com/wallyqs/hello-nats-go-mod/blob/master/go.mod

**Comment by biskit** [comment]
Hi @wallyqs your setup got me a lot further, but in the end hit the same message.

**Comment by wallyqs** [comment]
🤔 @biskit do you have imports in your repo for stan.go and nats.go? Those should also be updated

**Comment by biskit** [comment]
@wallyqs I do have lines line
`stan "github.com/nats-io/go-nats-streaming"`
and updating them to
`stan "github.com/nats-io/stan.go"`

seems to be what's been missing (along with your go.mod sample)

**Comment by coolyrat** [comment]
@biskit if you used the older version, you need to manually update go.mod.

**Comment by wallyqs** [comment]
Sharing in case anyone is still having issues such as:

```
go: github.com/nats-io/go-nats@v1.8.1: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"
go: github.com/nats-io/go-nats-streaming@v0.5.0: parsing go.mod: unexpected module path "github.com/nats-io/stan.go"
```

To fix it: 

1) Update your `go.mod` using the latest tags, for example for both NATS and NATS Streaming clients:

```ruby
module github.com/wallyqs/hello-nats-go-mod

go 1.12

require (
	github.com/nats-io/nats.go v1.8.1
	github.com/nats-io/stan.go v0.5.0
)
```

Or if want to import the NATS Server v2 to embed it, notice the `/v2` after the nats-server module name. If that is not present, then go modules will not fetch it and would accidentally end up with 1.4.1 version of the server.

```ruby
require (
	github.com/nats-io/nats-server/v2 v2.0.0
	github.com/nats-io/nats.go v1.8.1
)
```

2) Next, update the imports within the repo:

```sh
find ./ -type f -name "*.go" -exec sed -i -e 's/github.com\/nats-io\/go-nats-streaming/github.com\/nats-io\/stan.go/g' {} \;

find ./ -type f -name "*.go" -exec sed -i -e 's/github.com\/nats-io\/go-nats/github.com\/nats-io\/nats.go/g' {} \;

find ./ -type f -name "*.go" -exec sed -i -e 's/github.com\/nats-io\/nats-server/github.com\/nats-io\/nats-server\/v2/g' {} \;
```

3) (Recommended) Run Go fmt as that the rename will affect the proper ordering of the imports

**Comment by redthor** [comment]
:heart:  @wallyqs advice, thank you.

I made one small change to the `sed` command because, for some reason, the imports in the code I was [taking a look at](https://github.com/cyanly/gotrade) were just missing the `.go` at the end.

```
find ./ -type f -name "*.go" -exec sed -i -e 's#github.com\/nats-io\/nats"#github.com\/nats-io\/nats.go"#g' {} \;
```
