### ISSUE TITLE
go get stan.go fails

### ISSUE THREAD

**Issue by coffeefedora** [nats-io/stan.go#272]
this is similiar to https://github.com/nats-io/nats.go/issues/478  

i have  Go1.12.5 windows/amd64 on Windows 10 desktop.

my project is not inside a go/src tree.  

output from the command:

go get github.com/nats-io/stan.go
go: finding github.com/nats-io/stan.go v0.5.0
go: finding github.com/gogo/protobuf v1.2.1
go: finding github.com/kisielk/errcheck v1.1.0
go: finding github.com/kisielk/gotool v1.0.0
go: finding golang.org/x/tools v0.0.0-20180221164845-07fd8470d635
CreateFile github.com/nats-io/stan.go: The system cannot find the path specified.

**Comment by derekcollison** [comment]
`go get github.com/nats-io/stan.go/`

Note trailing slash.

**Comment by coffeefedora** [comment]
go get github.com/nats-io/stan.go/
CreateFile github.com/nats-io/stan.go: The system cannot find the path specified.

still fails

**Comment by coffeefedora** [comment]
go get github.com/nats-io/stan.go/@latest
go: downloading github.com/nats-io/stan.go v0.5.0
go: extracting github.com/nats-io/stan.go v0.5.0

this seems to have worked.  

the go get command should be able to work without requiring @latest trailing it.

**Comment by derekcollison** [comment]
I agree, they have an issue posted for a fix.

https://github.com/golang/go/milestone/95
