### ISSUE TITLE
read_last_sequence or read_from_sequence

### ISSUE THREAD

**Issue by isamuelson** [nats-io/stan.go#275]
is there a way to read the last message on a channel or a specific sequence from a channel?

**Comment by kozlovic** [comment]
Yes. Please check [this](https://github.com/nats-io/stan.go#subscription-start-ie-replay-options) and [this](https://nats-io.github.io/docs/developer/streaming/receiving.html).
You are looking at `StartWithLastReceived()` and `StartAtSequence()`.
