### ISSUE TITLE
DeliverAllAvailable behaviour

### ISSUE THREAD

**Issue by teivah** [nats-io/stan.go#278]
Hello,

This is an issue regarding the `DeliverAllAvailable` option. Basically, my use case would be as described [here](https://nats.io/blog/use-cases-for-persistent-logs-with-nats-streaming/) to build an internal state at startup. Yet, I would like to go a step further and set my application as ready once and only once I read all the messages. Otherwise, I would maybe receive a request while building my state and this would trigger an inconsistent response.

Is there any way to get notified once all the messages have been read?

Thanks

**Comment by ripienaar** [comment]
Messages will come in received order unless you are using a queue group. So new messages will come after old ones automatically.

**Comment by teivah** [comment]
Sorry, this is not my request. 

I want to build a state based on the messages in a queue. I want to set my application as ready only when I received all the messages. Is there any way to do so?

**Comment by ripienaar** [comment]
You could subscribe to latest - get the message ID - then unsubscribe and subscribe to all and once you get the same ID you are ready.

**Comment by teivah** [comment]
Okay sounds like a plan. Don't you think such a feature would have been a nice addition to stan? Like a particular option where I could provide a notification channel that would be used by stan?

**Comment by teivah** [comment]
Actually, no it does not work. To get the messageID I need to receive a message, so my application will be ready once I receive at least one message (to know the message ID then triggers the process you mentioned).

**Comment by kozlovic** [comment]
@teivah As mentioned, messages in the channel will be delivered in the order there were stored. I am not sure what "all messages" mean in a runtime situation. Say that when you create the subscription there are 100 messages in the channel, the server start to send those. Let's slow down things for explanation purpose. Say that your application receive one by one and then new messages are appended to the channel. What difference does it make to know that you received the 100th message now that there are say 150. If the messages constitute a state, the current state is the processing of those 150 messages.
Again, you have to understand that if you start a fresh non durable subscription, you are going to receive messages from the channel in the order they were stored, and your message callback is invoked serially with one message at a time. So there is no risk of having your application receive a new message while still processing the "old" ones.

**Comment by teivah** [comment]
@kozlovic Thanks for trying to help but this is not related to my problem. I ended up choosing something else, nevermind.

**Comment by derekcollison** [comment]
If I may ask, what did you end up choosing?
