### ISSUE TITLE
nats proto error

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [nats-io/stan.go#281]
Hello, I am getting this error

2019/09/17 10:10:46 proto: duplicate proto type registered: pb.PubMsg
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.PubAck
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.MsgProto
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.Ack
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.ConnectRequest
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.ConnectResponse
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.Ping
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.PingResponse
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.SubscriptionRequest
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.SubscriptionResponse
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.UnsubscribeRequest
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.CloseRequest
2019/09/17 10:10:46 proto: duplicate proto type registered: pb.CloseResponse
panic: proto: duplicate enum registered: pb.StartPosition

goroutine 1 [running]:
github.com/gogo/protobuf/proto.RegisterEnum(...)
	/home/yavuz/go/src/github.com/gogo/protobuf/proto/properties.go:509
github.com/nats-io/go-nats-streaming/pb.init.0()
	/home/yavuz/go/src/github.com/nats-io/go-nats-streaming/pb/protocol.pb.go:263 +0x537

**Comment by yavuzyurtbegendi** [comment]
it was because I had old repositories on my folder, If you get this error, just remove 
`github.com/nats-io/go-nats-streaming`
`github.com/nats-io/go-nats`

**Comment by kozlovic** [comment]
Thanks for letting us know. That will be helpful if someone gets the same error.
