### ISSUE TITLE
SubscribeSync in STAN

### ISSUE THREAD

**Issue by vonafor** [nats-io/stan.go#282]
I have a scenario when I want to use a synchronous subscription. NATS connection has _SubscribeSync_ method and _Subscription_ has _NextMsg_ method, but this feature is not present in STAN.

Is it achievable another way or I'm missing something?

**Comment by kozlovic** [comment]
Exploring adding the API for stan (with a Synchronous(bool) subscription option)...

**Comment by kozlovic** [comment]
We discussed this internally and since the focus will be on JetStream, we feel that adding a new API in the Streaming client libraries is not the best use of resources right now (we try to maintain the set set of features/APIs in all clients that we support).

Let me propose here what you could do to achieve this and let's discuss if this is a reasonable workaround or not:
```
// You can create this channel to any size, or the value of MaxInflight that you plan to use.
ch := make(chan *stan.Msg, 1024)
mcb := func(msg *stan.Msg) {
    ch <- msg
}
// This creates a subscription on "foo", using the above message handler
// and ask to receive all messages. We use manual acknowledgment mode
// since otherwise the message will be acknowledged in the callback before
// the code below may have a chance to process it.
sub, err := sc.Subscribe("foo", mcb, stan.DeliverAllAvailable(), stan.SetManualAckMode())
if err != nil {
    // handle error
}
// To get the next message, select on the `ch` channel and use a timeout..
// Would be easy to make this a function...
select {
    case m := <-ch:
        // Process message here...
        // Then ack it.
        m.Ack()
    case <-time.After(5 * time.Second):
        // Handle timeout here...
}
```

**Comment by vonafor** [comment]
Thank you for your proposal.

I thought about something like that, but the problem is I cannot keep messages in a channel infinitely and I am forced to handle messages after a subscription immediately, because in _AckWait_ seconds messages will be resent.

**Comment by kozlovic** [comment]
@vonafor Again, you can make that channel of size 1 so that the message callback will block after putting 1 message. 

> I cannot keep messages in a channel infinitely and I am forced to handle messages after a subscription immediately, because in AckWait seconds messages will be resent.

This is true even for current message callback. If the processing of your message takes longer than AckWait, the server will resend. You can also reduce MaxInflight to 1 to minimize that (but there will still be possibly the resend of that message...

**Comment by vonafor** [comment]
In my case a processing duration is dramatically less than a potential processing period. Therefore resending probabilities are not the same.

**Comment by kozlovic** [comment]
> In my case a processing duration is dramatically less than a potential processing period. Therefore resending probabilities are not the same.

I am sorry, I am not sure I understand... but my point is that your concern about redelivery does not change between the currently async subscription and the proposed synchronous using go channels as shown above. If I am missing something, could you detail a bit more? Thanks!

**Comment by CodeBlitz** [comment]
Can you let me know what the acronym STAN means?

**Comment by kozlovic** [comment]
The opposite of NATS, which does not stand for anything in particular :-)

**Comment by CodeBlitz** [comment]
@kozlovic no, it means something. It means that some developer thought it would be cute to confuse everyone about a complex solution instead of using a meaningful name.

**Comment by kozlovic** [comment]
@CodeBlitz ok... so there you go: https://docs.nats.io/faq#what-does-the-nats-acronym-stand-for

**Comment by kozlovic** [comment]
.. and STAN is really the code name for NATS Streaming which was the opposite of NATS philosophy (no persistence, at-most-once, etc.. vs persistence, at-least-once)

**Comment by kozlovic** [comment]
Closing for now, will re-open if needed.
