### ISSUE TITLE
Manual acknowledgement not testable 

### ISSUE THREAD

**Issue by fischor** [nats-io/stan.go#284]
https://github.com/nats-io/stan.go/blob/b13717edafc47e61e7999c9c8a078b173852655f/sub.go#L469-L474

I was trying to test my `stan.MsgHandler`s. I mocked the `Stan.Subscription` and `Stan.Conn` interfaces to do so. The `msg.Ack()` casts to the internal `subscription` type. Thus, it is not possible to test the `msg.Ack()` functionality of your code without having a real subscription. 

```
conn.Subscribe(channel, func(msg *stan.Msg){
   // my logic
   if err != nil {
        return
   }
   msg.Ack()
})
```
How would one test that code will acknowledge the message without setting up a real NATS connection?

**Comment by derekcollison** [comment]
In general we do not suggest trying to mock a system like NATS or STAN. If your tests are in Go you can easily embed a server or STAN server that uses memory store to run your tests.

**Comment by kozlovic** [comment]
What should `msg.Ack()` do though if the cast to `.(*subscription)` fails? Return `nil`, an `error`?
(it would be easy to add the test and return early if `msg.Sub` is not a STAN subscription implementation).

If you want to test the logic of your message handler code, maybe you should make it a function, say `processMsg(msg *stan.Msg)` and so you can unit test that. Do you need to setup a subscription to unit test the message handler logic? If you want to test integration with the streaming server, then as Derek mentioned, having a real server is probably easier.

```
processMsg(msg *stan.Msg) error {
   // your logic here
  return err
}
```
The above can easily be unit tested. Integrated in the actual code it becomes:
```
conn.Subscribe(channel, func(msg *stan.Msg){
   err := processMsg(msg)
   if err != nil {
        return
   }
   msg.Ack()
})
```
Alternatively, use a "wrapper" for Ack(), `msgAck(msg)` or similar (probably would need to pass some state), and decide to ack (if real subscription) or not (if mock).

Here is some other PR that basically asked for the same but was rejected:
https://github.com/nats-io/stan.go/pull/195

**Comment by kozlovic** [comment]
Closing for now, will re-open if needed.
