### ISSUE TITLE
Need a better error message when using the wrong cluster ID

### ISSUE THREAD

**Issue by politician** [nats-io/stan.go#285]
When connecting to a cluster with the wrong cluster ID, the error returned from `stan.Connect` is `stan: connect request timeout`.

I spent multiple hours tearing apart my network topology trying to figure out a routing error when the problem was using the wrong cluster ID.

**Comment by kozlovic** [comment]
Sorry about that. The streaming server is listening to a special subject: `_STAN.<cluster ID>.discover`. The client library is sending a NATS request to the subject `_STAN.<cluster ID>.discover` with the cluster ID that is provided in the `stan.Connect()` call. So the server really never receives the request (there is no way it can say to the client: you got the wrong cluster ID). So the client really gets a timeout. 
All that being said, maybe it would help if we modify `ErrConnectReqTimeout` to include a hint on the possibly wrong cluster ID, something like this:
```
       ErrConnectReqTimeout = errors.New("stan: connect request timeout (possibly wrong cluster ID?)")
```
Now obviously, there will be cases where it is a legitimate timeout in that the cluster ID matches but the server is either too busy, the timeout is too small, or there are network issues.

/cc @derekcollison interested in your opinion

**Comment by derekcollison** [comment]
This is similar to other requests when trying to debug the system in such a way that we want to ask the system "is someone listening"? We have added beta support for this general feature as part of the system account.

https://github.com/nats-io/nats-server/commit/b98b75b1661a6a5d7de69bc75be77f686c90c108#diff-99912d293d6035363c36ff4a9774ca31R29

Also, in JetStream we are looking at actively answering requests like you mention above to detect this error.

As more of a historical approach you can also, if you control the servers, start them in debug and trace mode and watch the interactions when your application launches.

I think the approach above, allowing you to ask about registered interest, will be the longer term solution to debugging the system from an interest standpoint.
