### ISSUE TITLE
timer is too many？

### ISSUE THREAD

**Issue by lonerwolf** [nats-io/stan.go#294]
in publishAsync
a.t = time.AfterFunc(ackTimeout, func() {。。。
when op 100000time in one second then make 100000 timer ,can it replace by a timewheel?

**Comment by kozlovic** [comment]
@lonerwolf  Thank you for the report. Will have a look as soon as I can. Did you experience any issue with the number of timers or is just based on code inspection?

**Comment by lonerwolf** [comment]
> just based on code inspection

just based on code inspection

**Comment by kozlovic** [comment]
@lonerwolf I had a PR to eliminate the need of timer-per-publish call, but we really the number of timers should not be more than the MaxPubAcksInflight (which by default is 1024), regardless of how "fast" you are publishing number of messages per second. But we will re-evaluate if needed. Closing this issue for now.
