### ISSUE TITLE
PublishMsg equivalent

### ISSUE THREAD

**Issue by biskit** [nats-io/stan.go#300]
Is there a streaming equivalent of PublishMsg that will support an optional `reply-to`?

**Comment by ripienaar** [comment]
streaming messages don't really have a concept of reply-to imo

**Comment by biskit** [comment]
one still likes to publish a reply to someone who's listening... so should that be coded as part of message?

**Comment by ripienaar** [comment]
conceptually streaming isn't about a conversation, its about observing events and reacting independently, its inherently asynchronous and about uncoupled communications.

You'd need to do something in your payload if you need this I am afraid

**Comment by kozlovic** [comment]
> one still likes to publish a reply to someone who's listening

But that's the thing, sending a "reply" would go to a channel, that doesn't make any sense in streaming. I would argue that if the sender app needs to wait for confirmation from the subscription itself, then use core NATS req/reply, not streaming. In streaming this "reply" would be in a channel for everybody subscribing on this channel to see..
