### ISSUE TITLE
Correctness of stan-bench/main.go

### ISSUE THREAD

**Issue by hsahuntnx** [nats-io/stan.go#301]
@kozlovic stan-bench/main.go starts publisher and subscriber simultaneously on the same topic that means the subscriber has to wait for the publisher to publish the message (since the subscriber is faster than the publisher). For example:- 
When we've less number of producer and a large number of subscriber then (Let's assume 1:25 ratio) subscriber benchmark number will suffer as all the subscriber has to wait for the publisher to finish.
Is this expected behavior?

**Comment by kozlovic** [comment]
@hsahuntnx No, the subscriber won't wait that the publisher to finish. As soon as messages become available the server will send them to the subscribers. Also, subscriber's start time is captured when the first message (for this subscriber) is received: 
https://github.com/nats-io/stan.go/blob/e2d4c025a5eea41d9566dc8e978c7ee697470b64/examples/stan-bench/main.go#L208
https://github.com/nats-io/stan.go/blob/e2d4c025a5eea41d9566dc8e978c7ee697470b64/examples/stan-bench/main.go#L232
