### ISSUE TITLE
Sequence Number

### ISSUE THREAD

**Issue by biskit** [nats-io/stan.go#302]
Hi,
I've looked here before asking as this...

I have a _Regular_ subscription with _Manual Ack_ and _Starting Sequence_.
- Receive a message and ack
- store message id
- till client crashes and my last stored id is lower than last ack'd id

how do i start with my last stored lower id again and get all that was lost by the client.

thanks

**Comment by kozlovic** [comment]
Why not using durable subscription? This is all done for you.
If the answer is that durable name must be unique and you have many of these clients, then on first start generate a unique durable name, store it, and then reuse that name on restart.

If you store the sequence of message that is received, then use that sequence +1 when restarting (with `StartAtSequence()`). I guess I must not understand your question..

**Comment by biskit** [comment]
Thanks for reply @kozlovic. I need to start at a number earlier. If current sequence number is N and last value I have is from sequence number N-M, I need to start at N-M.

**Comment by kozlovic** [comment]
Use `StartAtSequence()` where you pass the sequence number you want to start from..

**Comment by biskit** [comment]
I do. My application has gone away, and this being a Regular subscription the client has unsubscribed/closed. Will still asking `StartAtSequence()` get me from where I fell off?

**Comment by kozlovic** [comment]
Again, you should probably use a Durable subscription, but what I am saying is that if you persist the last processed sequence, then on restart, load that value and create the subscription with StartAtSequence() with this value (or +1) and you will receive messages from that position onward. If you use channel limits and messages have been removed by then, this call will set it to the first avail seq in the channel.

**Comment by tpihl** [comment]
Hi.

I use a similar pattern. Ack last of all solved it for me, after processing and storing last processed msg (i actually publish to a .processed subject.

When starting, i read the last msg on .processed and start from there. (So i actually get the last msg again just to verify that it's the same message and that the server has not been reset).

/T
