### ISSUE TITLE
Create connection from options

### ISSUE THREAD

**Issue by jeroenrinzema** [nats-io/stan.go#303]
Inside the NATS core library is it possible to create a new connection from a set of predefined [Options](https://github.com/nats-io/nats.go/blob/master/nats.go#L975). It would be great if a similar implementation could be added to this libaray.

I would love to hear your thoughts about this.

**Comment by kozlovic** [comment]
Actually this way of creating options is no longer suggested. Instead we have been pushing for this version instead: https://github.com/nats-io/nats.go/blob/6dfc35499dd0be83f541f271f78715d7d3a72c09/nats.go#L546

Any reason or use case where you think you would need to be able to create the STAN connection from its options? If option setters are missing, they could be added. You can also always create an option without having to wait for the library to have it.

**Comment by jeroenrinzema** [comment]
Thank you for your response.

I am working on a transportation implementation for `go-micro` using NATS streaming. I would like to set the passed values from `go-micro` and use them to construct a new connection. Currently, this implementation uses the `Connect` method to [construct a new NATS connection](https://github.com/micro/go-plugins/blob/master/transport/nats/nats.go#L397).

I could try out and wrap the STAN options inside the transport implementation for them to be used/set during configuration.

```go
import (
  "time"
  "github.com/micro/go-micro/transport"
  "github.com/stan/implementation"
)

implementation.NewTransporter(
  transport.Addrs("nats://localhost:4222"),
  implementation.ConnectTimeout(time.Second),
)
```

**Comment by kozlovic** [comment]
You would need to create an array of `stan.Option` and append to this array the corresponding option function based on the given `stan.Options`, then pass this array to the `Connect()` call.
