### ISSUE TITLE
If the durable queue group guarantees in-order messages after all consumers restart?

### ISSUE THREAD

**Issue by ZiyunYang** [nats-io/stan.go#308]
Hi, I try to implement a pub-sub messaging system by using go-micro + stan broker. A producer pub messages and several consumers form a durable queue group to sub messages. When producer and consumers are both online, the messages are in-order. Then the producer continue to work while all consumers are shut down. When the consumer restart, messages it receives will be out-of-order.

I wonder if stan guarantee the order of messages after all consumers restart? Or is it a bug?

**Comment by derekcollison** [comment]
Yes the messages should be delivered in order. Are you sure Go-Micro is using STAN and not just plain NATS?

**Comment by kozlovic** [comment]
But already if you say a durable queue group, are you using more than one member in that group? If so, order is already not guaranteed in that the server distributes messages from the order the producer has sent them, but since they are sent to different subscriptions (possibly different processes), you cannot really expect any order.
If you had only one member, then I suspect that you did not call connection.Close() when the member was stopped. Since there is no direct TCP connection between server and client (https://docs.nats.io/nats-streaming-concepts/relation-to-nats), the server does not know. When you restart your queue member, it is actually the second member (until the server realizes that the first is has been stopped).

**Comment by ripienaar** [comment]
If it's a group, even with just 1 subscriber it's not going to get reliable ordering ime, only if you use a plain durable

**Comment by ZiyunYang** [comment]
> If it's a group, even with just 1 subscriber it's not going to get reliable ordering ime, only if you use a plain durable

I think @kozlovic is correct. If just 1 subscriber in a group and it call connection.Close() when the subscriber stops, the messages will be in-order when the only subscriber restarts.

**Comment by kozlovic** [comment]
But you do understand that if you have a group of 1, then there is no difference compared to a durable non-queue subscription. And as soon as you will make the group bigger than 1 member, then you cannot expect ordering processing in your subscriptions...

**Comment by ripienaar** [comment]
The behaviour of how unacked messages that gets redelivered is different in groups vs no grouped. 

Suggest you test the ordering of those too

**Comment by vtolstov** [comment]
> Yes the messages should be delivered in order. Are you sure Go-Micro is using STAN and not just plain NATS?

i'm wrote stan plugin for go-micro =)

**Comment by ZiyunYang** [comment]
> But you do understand that if you have a group of 1, then there is no difference compared to a durable non-queue subscription. And as soon as you will make the group bigger than 1 member, then you cannot expect ordering processing in your subscriptions...

Yes, make sense!
Let me verify if my understanding is correct...Here is my go-micro+stan demo: https://github.com/ZiyunYang/gomicro_demo/tree/master/gomicro_durablequeue

At first, I didn't call connection.Close() when subscribers are stopped. So for even one subscriber, the message was out-of order. The test result is something like this.
![image](https://user-images.githubusercontent.com/47910618/79899725-c15b1780-843f-11ea-8954-341716904583.png)


After I call connection.Close(). The order within one subscribe can be guaranteed. However, the relative order between different subscribers can't be guaranteed.(right???)  The test result is something like this.
![image](https://user-images.githubusercontent.com/47910618/79899774-d172f700-843f-11ea-9387-06ae954e171f.png)

If my understanding is correct, another question is if I'm really care about the the relative order between different subscribers of the same queue group, what can I do?  Can I record the last received position, comparing last received position to now receiving message position to decide if this message should be processed and acked, and update position after manually ack message?

**Comment by ZiyunYang** [comment]
> redelivered

You mean Unsubscribe() and Close()? Can you be more specifictly?

**Comment by kozlovic** [comment]
But you "can't" rely on ordering when there is more than one consumer. They are different processes, so how can you rely on the process A to process a message before process B? Server may send message 1 to process A first, then message 2 to process B but you have no control on when the message callback in each process is going to be invoked.

So if you rely on processing ordering you must not use more than one subscription.

(also, as you have seen if you don't call Close() you will see that out-of-order redeliveries even when there is only "1" member, but you can't guarantee that your application is not going to crash - when you can't call Close()). So again, if you rely on strict ordering, don't use multiple consumers (queue group here).

**Comment by ZiyunYang** [comment]
@kozlovic   Understood. So if I have multiple instances of the same service to subscribe a topic and I rely on strict ordering. I need to set the service as stateful service, assign clientID for every instance  and use only one subscription.

**Comment by kozlovic** [comment]
Yes, if you have a single channel and ordering processing is important, you can't load balance the processing of it because then you can't control how/when each subscription is doing its work. So I would recommend in that case unique clientID for every instance and use a durable subscription (non queue), so you also protect against a crash (app not calling Close()).

**Comment by ZiyunYang** [comment]
@kozlovic  Thank you so much! I'll figure out if my feature really need strict ordering and then resolve the issue.

**Comment by kozlovic** [comment]
Great! Don't hesitate to contact us again if you have any other question. Closing this one for now.
