### ISSUE TITLE
Channel API

### ISSUE THREAD

**Issue by moon-bits** [nats-io/stan.go#309]
Hi guys,

We are trying to use STAN, since we need to ensure that all messages are being processed. Yet, when we look at the API (in comparison to nats-go), it seems that there is no channel interface like we have in nats-go:

`func (c *EncodedConn) BindRecvQueueChan(subject, queue string, channel interface{}) (*Subscription, error)`

or the _EncodedConn_ that gives us the de-/serialisation feature. 

Am I missing here anything?

Thanks!

**Comment by kozlovic** [comment]
No you are not missing anything. Those features are not part of NATS Streaming.
The streaming library uses protobuf to send/receive streaming messages. Payload encoding/decoding is left to the user.

**Comment by derekcollison** [comment]
There is not too much craziness to the NATS Encoded Connection if you wanted to layer on top and do channels etc.

**Comment by moon-bits** [comment]
Thanks to both of you!
