### ISSUE TITLE
nats streaming received message after stan timeout 

### ISSUE THREAD

**Issue by pikot** [nats-io/stan.go#312]
I have made some tests with nats-streaming and I get strange behavior. I don't understand how to fix it.

workflow

1. run nats-streaming 
2. run application (initialised over stan), ala
```
         _cn, err := stan.Connect( clusterID, clientID, stan.Pings(10, 2), stan.PubAckWait( PubAckWait ),
                                 stan.NatsURL( URL ),
                                 stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
                                         fmt.Printf("Connection lost, reason: %v\n", reason)
         }) )
```
it means i have 

```
                        nats.MaxReconnects(-1),
                        nats.ReconnectBufSize(-1)
```

3. Publish message via application, nats-streaming receive message as expected
4. Send SIGSTOP to nats-streaming server (try to emulate some network problem)
**5.** Publish message via application (before ping timeout occur) -  timeout happened, as expected  
6. Send SIGCONT to nats-streaming server
7. Nats-streaming server received message from step **5.** :\ i don't expect it, a guess it should be discarded.

As i said reconnect buf size set in -1,  but nats streaming server received message after timeout in connect to nats. If  ping timeout happened, all ok. Any ideas how to fix it?

**Comment by derekcollison** [comment]
The network is still in place in terms of TCP/IP so it just waits in a buffer to be delivered. This is how TCP/IP works. We have additional ping/pongs that are designed to detect stalled connections but sounds like your test did not run long enough with STAN paused to trigger.

**Comment by pikot** [comment]
Yep, this was network buffers. Thanks for hint!
