### ISSUE TITLE
How to receive sequence of last send message in subscriber ?

### ISSUE THREAD

**Issue by LokkaPatel** [nats-io/stan.go#319]

**Comment by kozlovic** [comment]
To be sure I understand what you are asking: you would want to get the sequence of the current last message in the channel when the subscription is created and get that back from the Subscription object?
If this what you are asking this has been asked in NATS Streaming server (https://github.com/nats-io/nats-streaming-server/issues/175). It would require a modification in the protocol in both the client and the server.

**Comment by LokkaPatel** [comment]
> To be sure I understand what you are asking: you would want to get the sequence of the current last message in the channel when the subscription is created and get that back from the Subscription object?
> If this what you are asking this has been asked in NATS Streaming server ([nats-io/nats-streaming-server#175](https://github.com/nats-io/nats-streaming-server/issues/175)). It would require a modification in the protocol in both the client and the server.
