### ISSUE TITLE
if channel is not created .Sequence of last message through channel must be 0.You won't able to get sequence from subscribing using stan.StartWithLastReceived() .Is there any other way to get sequence of last message send through channel ?

### ISSUE THREAD

**Issue by LokkaPatel** [nats-io/stan.go#320]

**Comment by kozlovic** [comment]
StartWithLastReceived() does not guarantee that your subscription will receive a message if the channel has no message or did not exist prior to starting your subscription.
Closing this one since you have opened #321 and I have given a bit of details there.
