### ISSUE TITLE
After reconnect: PublishAsync throws "stan: connection closed"

### ISSUE THREAD

**Issue by KidLinus** [nats-io/stan.go#322]
I'm restarting my nats server and after the NATS reconnects to the server every call to publish still throws "stan: connection closed". I connecting like so: `stan.Connect(serverID, id, stan.NatsConn(nc), stan.Pings(1, 60*10))`
I'm subscribing like this: `QueueSubscribe(topic, "uop-queue", func(msg *stan.Msg) { ch <- msg }, stan.DurableName(topic), stan.MaxInflight(50), stan.SetManualAckMode())`
I'm pulbishing like this: `s.conn.PublishAsync(topic, []byte("msg"), nil)`

Am i missing somthing here? I've gone through all the docs i can find about reconnecting and I'm drawing a blank.

**Comment by kozlovic** [comment]
Note that you have configured the client to send a ping every second and fail after 600 missed responses. If you get a failure that the connection is closed, I suspect that you are restarting the NATS Streaming server with memory store, which means that no state is persisted and the newly restarted server rejects the client ping.
I would recommend that you setup the connection lost handler to see if that is the case. Read more about it here: https://github.com/nats-io/stan.go#connection-status

**Comment by KidLinus** [comment]
> Note that you have configured the client to send a ping every second and fail after 600 missed responses. If you get a failure that the connection is closed, I suspect that you are restarting the NATS Streaming server with memory store, which means that no state is persisted and the newly restarted server rejects the client ping.
> I would recommend that you setup the connection lost handler to see if that is the case. Read more about it here: https://github.com/nats-io/stan.go#connection-status

You're a genius. I will try disk store out later today and see if that fixes the issue. What a caveat

**Comment by kozlovic** [comment]
One of the motivation for Pings() and ConnectionLostHandler was that new users of NATS Streaming would actually often restart the server with mem store and report that they were no receiving any new message. Without the Pings feature, the client would not fail but obviously stop receiving messages because the restarted server did not know about the client and its subscriptions.

**Comment by KidLinus** [comment]
That's all great, but you might want to add a note about mem nats in the docs. Could save you time, if not i hope the next lost soul finds this issue. I'll close it now and reopen if it was not the issue. Have a nice weekend!

**Comment by kozlovic** [comment]
@KidLinus Thanks for the feedback, and completely agree on the doc. Could you please help me find the right place in the doc (https://docs.nats.io/ and/or this README) where you would have expected to find this piece of information? Thanks!

**Comment by KidLinus** [comment]
I think that this excelent section https://docs.nats.io/nats-streaming-server/configuring/persistence
should be referenced in the godoc or in the readme of the project. I also find the category "Configuring" missleading, I'd love to have this information here: https://docs.nats.io/nats-streaming-concepts/client-connections

Reconnection is a huge deal breaker for us, moving away from RabbitMQ for that specific reason. It is clearly stated and described in vanilla NATS, i think streaming should highlight it a bit more and especially where it differs from just running NATS.

**Comment by kozlovic** [comment]
@KidLinus Sorry for the delay. I have copied what is in "configuring/persistence" to the "client connections" page. Check out https://github.com/nats-io/nats.docs/pull/133.
Also, added some notes about reconnection in this repo: https://github.com/nats-io/stan.go/pull/323. Would appreciate any feedback in what you think is missing, etc..

**Comment by KidLinus** [comment]
Just read through everything and I think it it looks great. Especially this section https://github.com/nats-io/nats.docs/pull/133/files

Thank you for the help!
