### ISSUE TITLE
Cannot receive message published asynchronous  on subscription

### ISSUE THREAD

**Issue by sergevonage** [nats-io/stan.go#346]
I run examples from the `examples` folder. If I run 
```
go run stan-pub/main.go msg hello
```
it works proper:
```
Connected to nats://127.0.0.1:4222 clusterID: [my-stan] clientID: [stan-sub]
Listening on [msg], clientID=[stan-sub], qgroup=[] durable=[]
Received a message: hello
```
But I run it asynchronous:
```
go run stan-pub/main.go -a true msg hello
```
I don't receive anything. 

Are there some additional configuration to be subscribed for message published asynchronous?

**Comment by kozlovic** [comment]
This is because the command to send is wrong. It should be:
```
go run stan-pub/main.go -a msg hello
```
or
```
go run stan-pub/main.go -a=true msg hello
```
You were otherwise sending to the channel name "true". You can run the server with `-SDV` and see that happening.

**Comment by sergevonage** [comment]
Yeah, thank, sorry for misunderstanding
